---
abstract: 'Parse nice HTML files without needing a compiler'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Parser-Simple
provides:
  HTML::Parser::Simple:
    file: lib/HTML/Parser/Simple.pm
    version: 1.08
  HTML::Parser::Simple::Attributes:
    file: lib/HTML/Parser/Simple/Attributes.pm
    version: 1.08
  HTML::Parser::Simple::Reporter:
    file: lib/HTML/Parser/Simple/Reporter.pm
    version: 1.08
requires:
  Tree::Simple: 0
  perl: 5.006
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.08
